spring:
  datasource:
  url:
  username: postgres
  password: islam20011
  mail:
    host: "smtp.mail.ru"
    username: "markuysa.study@mail.ru"
    password: "73q7PFntNRAT650asib3"
    port: "465"
    protocol: "smtps"



